use std::sync::Mutex;
use tauri::Manager;
use tauri_plugin_shell::{process::CommandChild, ShellExt};

/// Holds the spawned Python backend process so it stays alive with the app.
pub struct BackendProcess(pub Mutex<Option<CommandChild>>);

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .setup(|app| {
            // Spawn the bundled Python FastAPI backend as a sidecar.
            // The binary must live in src-tauri/binaries/ with a target-triple
            // suffix (generated by scripts/build-sidecar.sh).
            let sidecar_cmd = app
                .shell()
                .sidecar("gamecut-backend")
                .expect("gamecut-backend sidecar not configured in tauri.conf.json");

            let (_rx, child) = sidecar_cmd
                .args(["--host", "127.0.0.1", "--port", "8000"])
                .spawn()
                .expect("Failed to start GameCut backend process");

            app.manage(BackendProcess(Mutex::new(Some(child))));
            Ok(())
        })
        .on_window_event(|window, event| {
            // Kill the backend when the last window is destroyed.
            if let tauri::WindowEvent::Destroyed = event {
                if let Some(state) = window.app_handle().try_state::<BackendProcess>() {
                    if let Ok(mut guard) = state.0.lock() {
                        if let Some(child) = guard.take() {
                            let _ = child.kill();
                        }
                    }
                }
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
